### PR TITLE
Move to ESLint

### PR DESCRIPTION
**Pull request by YoranBrondsema**
WIP for https://github.com/bustle/mobiledoc-kit/issues/562.

1. The first step was to adapt https://github.com/bustle/broccoli-test-builder to use ESLint instead of JSHint (see https://github.com/bustle/broccoli-test-builder/pull/2). I got this working, although a new release or a fork of https://github.com/bustle/broccoli-test-builder should be made based on that PR.
2. I generated a ESLint using the wizard when `eslint --init` is run. It based it on the current files in `src/` and it might not be the exact rules that the projects wants.
3. Fixing the violations. It's probably best to deactivate a whole bunch of rules at first to make ESLint pass, and then enable the rules one by one.

@mixonic let me know your thoughts!

### CODE REVIEW

**Comment by bantic** [comment]
@YoranBrondsema This looks great to me. There was only one eslint error in non-test code that I could find. The majority of the rest appear to be "no-unused-vars".
Is it possible to have a separate config for tests? I would be fine as a first step to disable some more of these for the test files.

**Comment by YoranBrondsema** [comment]
@bantic Alright pushed a few changes.

* Updated `broccoli-test-builder` to use the version you just released (0.4.0).
* Disabled the violating rules. I made a separate `.eslintrc` for the tests.
* Removed stuff related to JSHint, i.e. `.jshintrc` but also the `// jshint:ignore` lines that were spread throughout.

The rules to look at that were violating in the app are:

* no-case-declarations
* no-console
* no-extra-boolean-cast
* no-unused-vars

And the ones specifically for the tests are in `tests/.eslintrc`.

The linter passes now. Maybe those rules can be looked at in a next PR?

**Comment by YoranBrondsema** [comment]
I'm working on fixing those now.

**Comment by YoranBrondsema** [comment]
@bantic I addressed those rules from my previous comment so this PR should be ready for review now.

**Comment by bantic** [comment]
@YoranBrondsema thanks, this is great. There's a conflict with the `yarn.lock` after I merged #564. Once that is resolved this is good-to-go imo. Happy to move over to eslint. :)

**Comment by YoranBrondsema** [comment]
@bantic Great, fixed the conflict. Should be good to go now.

**Comment by bantic** [comment]
thank you very much @YoranBrondsema !

**Pull request merged**
