### PR TITLE
Fix IME issue

### LINKED ISSUE #548: Entering logograms issues in macOS
This is the issue from the Ghost project.
https://github.com/TryGhost/Ghost/issues/8319

(The issue was submitted by @mach)

# Issue Summary

On Ghost Alpha's new text editor, Japanese text can't be typed correctly with Japanese IME (input method).

image

Steps to Reproduce

    Select Japanese IME (either Apple's JapaneseIM or Google's Japanese IME)
    Type "watasi"
    Press Enter key

Expected Result

At step 2: "watasi" should be converted to "わたし"
At step 3: "わたし" should be converted to "私"
Actual Result

At step 2: "watasi" is converted to "wあたし"
At step 3: "wあたし" is converted to "w"
Technical details:

    Ghost Version: 1.0.0-alpha.19
    Node Version: v6.10.2
    Browser/OS: Google Chrome / macOS Sierra
    Database: MySQL 5.7.17

### LINKED ISSUE #589: Input on android has a bug
Android:
When inserting text in the editor, after the first char the cursor moves back to start of editor area (instead than remaining after the inserted char), and after inserting another char the first char is duplicated.
------------------
the cursor is shown like '|'
the area delimiter is '<<' and '>>'
-----
bug :
-----
1) text area: <<>>
2) action: <press char 'a'>
3) text area: <<|A>>
4) action: <press char 'b'>
5) text area: <<Ab|A>>
.. and so on

### PR DESCRIPTION
**Pull request by huaying**
Fix #548 and probably fix #589 as well

Love [ghost](https://github.com/TryGhost/Ghost) but sadly see the bug affect a lot of users.
Can someone also help test it? It works for me in my local (I am a traditional Chinese IME user).

Hope the PR can be merged asap. (no tests though)

ref 
#661 

https://github.com/TryGhost/Ghost/issues/11460

### CODE REVIEW

**Comment by iLoveBug** [comment]
It's real happy that someone else is trying to resolve this problem almost at the same time. I have spent more than 1 day to invest the problem.

You can try my solution: https://github.com/TryGhost/mobiledoc-kit/pull/11, verified on my Mac OS, Chrome.

**Comment by supersetcc** [comment]
It works for me though. (I am a traditional Korean IME user)

**Comment by jsxzljx** [comment]
> It's real happy that someone else is trying to resolve this problem almost at the same time. I have spent more than 1 day to invest the problem.
> 
> You can try my solution: [TryGhost#11](https://github.com/TryGhost/mobiledoc-kit/pull/11), verified on my Mac OS, Chrome.

hi, would you please share how to manually assign using the dev-version of mobiledoc-kit when building ghost? The ghost-CLI always pull the latest version and building the final scripts, I'm wondering how to use specific branch/commit to build. As you know, it seems no one is going to merge this PR in a short time (has been opened for 6 months).

**Comment by ZeeJab** [comment]
Superseded by #738

**Pull request closed without merging**
