### PR TITLE
Document inputModeDidChange() lifecycle hook

### PR DESCRIPTION
**Pull request by YoranBrondsema**
This hook was not documented in the README and I believe it's important enough to have it there.

### CODE REVIEW

**Comment by YoranBrondsema** [comment]
Not sure what happened that made the build fail? The log for the build on Travis is empty for me :/

**Comment by YoranBrondsema** [comment]
OK, seems to an issue with `wd` which is a dependency of `saucie`. The version in `yarn.lock` (1.1.3) should be OK (see https://github.com/johanneswuerbach/saucie/issues/65) so maybe a refresh of the cache on Travis would solve the issue?

**Comment by YoranBrondsema** [comment]
Issue here: https://github.com/bustlelabs/mobiledoc-kit/issues/557

**Comment by bantic** [comment]
@YoranBrondsema Thanks for this...I've kicked the Travis build. The repo rename from bustlelabs -> bustle seems like it might also have confused Travis. Here's the in-progress build: https://travis-ci.org/bustle/mobiledoc-kit/builds/226236041

**Comment by YoranBrondsema** [comment]
@bantic Cool thanks! There are a few other small PRs that are ready for review :-)

**Comment by bantic** [comment]
thanks @YoranBrondsema ! Rebuilding travis fixed the tests. :)

**Comment by bantic** [comment]
released in [v0.10.16](https://github.com/bustle/mobiledoc-kit/blob/master/CHANGELOG.md#01016-2017-05-25)

**Pull request merged**
